export const mockGroups = [
  {
    id: '1',
    name: 'Customer Feedback',
    description: 'Forms for collecting customer feedback and reviews',
    color: 'bg-blue-600',
    user_id: 'user1',
    created_at: '2024-01-15T10:00:00Z',
    form_count: 3,
  },
  {
    id: '2',
    name: 'Event Registration',
    description: 'Registration forms for various events and workshops',
    color: 'bg-indigo-600',
    user_id: 'user1',
    created_at: '2024-01-14T10:00:00Z',
    form_count: 2,
  },
  {
    id: '3',
    name: 'Contact Forms',
    description: 'General contact and inquiry forms',
    color: 'bg-purple-600',
    user_id: 'user1',
    created_at: '2024-01-13T10:00:00Z',
    form_count: 1,
  },
  {
    id: '4',
    name: 'Surveys',
    description: 'Customer satisfaction and market research surveys',
    color: 'bg-green-600',
    user_id: 'user1',
    created_at: '2024-01-12T10:00:00Z',
    form_count: 4,
  },
];

export const mockForms = [
  {
    id: '1',
    title: 'Product Feedback Form',
    description: 'Collect feedback about our products',
    group_id: '1',
    user_id: 'user1',
    created_at: '2024-01-15T10:00:00Z',
    fields: [
      {
        id: '1',
        label: 'Product Name',
        type: 'text',
        required: true,
        placeholder: 'Enter product name',
      },
      {
        id: '2',
        label: 'Rating',
        type: 'select',
        required: true,
        options: [
          '1 - Poor',
          '2 - Fair',
          '3 - Good',
          '4 - Very Good',
          '5 - Excellent',
        ],
      },
      {
        id: '3',
        label: 'Comments',
        type: 'textarea',
        required: false,
        placeholder: 'Additional feedback',
      },
    ],
  },
  {
    id: '2',
    title: 'Service Review',
    description: 'Rate our customer service',
    group_id: '1',
    user_id: 'user1',
    created_at: '2024-01-14T10:00:00Z',
    fields: [
      {
        id: '1',
        label: 'Service Representative',
        type: 'text',
        required: true,
        placeholder: 'Representative name',
      },
      {
        id: '2',
        label: 'Service Rating',
        type: 'select',
        required: true,
        options: [
          '1 - Poor',
          '2 - Fair',
          '3 - Good',
          '4 - Very Good',
          '5 - Excellent',
        ],
      },
    ],
  },
  {
    id: '3',
    title: 'Bug Report',
    description: 'Report issues with our software',
    group_id: '1',
    user_id: 'user1',
    created_at: '2024-01-13T10:00:00Z',
    fields: [
      {
        id: '1',
        label: 'Bug Title',
        type: 'text',
        required: true,
        placeholder: 'Brief description of the bug',
      },
      {
        id: '2',
        label: 'Steps to Reproduce',
        type: 'textarea',
        required: true,
        placeholder: 'Detailed steps to reproduce the issue',
      },
      {
        id: '3',
        label: 'Severity',
        type: 'select',
        required: true,
        options: ['Low', 'Medium', 'High', 'Critical'],
      },
    ],
  },
  {
    id: '4',
    title: 'Conference Registration',
    description: 'Register for our annual conference',
    group_id: '2',
    user_id: 'user1',
    created_at: '2024-01-12T10:00:00Z',
    fields: [
      {
        id: '1',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'Enter your full name',
      },
      {
        id: '2',
        label: 'Email',
        type: 'email',
        required: true,
        placeholder: 'Enter your email',
      },
      {
        id: '3',
        label: 'Company',
        type: 'text',
        required: false,
        placeholder: 'Company name',
      },
      {
        id: '4',
        label: 'Dietary Restrictions',
        type: 'textarea',
        required: false,
        placeholder: 'Any dietary restrictions or allergies',
      },
    ],
  },
  {
    id: '5',
    title: 'Workshop Sign-up',
    description: 'Sign up for technical workshops',
    group_id: '2',
    user_id: 'user1',
    created_at: '2024-01-11T10:00:00Z',
    fields: [
      {
        id: '1',
        label: 'Workshop Selection',
        type: 'select',
        required: true,
        options: [
          'React Fundamentals',
          'Advanced TypeScript',
          'Node.js Best Practices',
          'Database Design',
        ],
      },
      {
        id: '2',
        label: 'Experience Level',
        type: 'select',
        required: true,
        options: ['Beginner', 'Intermediate', 'Advanced'],
      },
    ],
  },
  {
    id: '6',
    title: 'General Contact',
    description: 'Get in touch with our team',
    group_id: '3',
    user_id: 'user1',
    created_at: '2024-01-10T10:00:00Z',
    fields: [
      {
        id: '1',
        label: 'Name',
        type: 'text',
        required: true,
        placeholder: 'Your name',
      },
      {
        id: '2',
        label: 'Email',
        type: 'email',
        required: true,
        placeholder: 'Your email',
      },
      {
        id: '3',
        label: 'Subject',
        type: 'text',
        required: true,
        placeholder: 'Message subject',
      },
      {
        id: '4',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: 'Your message',
      },
    ],
  },
];
